export const ADD_SPRINTS = 'SPRINT:ADD'

export const FETCH_SPRINTS = 'SPRINT:FETCH'
export const FETCHING_SPRINTS = 'SPRINT:FETCHING'
export const FETCHED_SPRINTS = 'SPRINT:FETCHED'

export const FETCH_SPRINT = 'SPRINT:FETCH_ONE'

export const CREATE_SPRINT = 'SPRINT:CREATE'
export const CREATING_SPRINT = 'SPRINT:CREATING'
export const CREATED_SPRINT = 'SPRINT:CREATED'
export const CREATE_SPRINT_ERROR = 'SPRINT:CREATE_ERROR'
