export const FETCH_TEAMS = 'TEAM:FETCH'
export const FETCH_TEAMS_IF_NEEDED = 'TEAM:FETCH_IF_NEEDED'
export const FETCHING_TEAMS = 'TEAM:FETCHING'
export const FETCHED_TEAMS = 'TEAM:FETCHED'

export const CREATE_TEAM = 'TEAM:CREATE'
export const CREATING_TEAM = 'TEAM:CREATING'
export const CREATED_TEAM = 'TEAM:CREATED'
export const CREATE_TEAM_ERROR = 'TEAM:CREATE_ERROR'
